[workspace]
members = [
    "prototype",
    "production"
]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
debug = false
panic = "abort"
overflow-checks = false
codegen-units = 1