[package]
name = "intc"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
prototype = { path = "../prototype" }
llvm-sys = "160"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"

[dev-dependencies]
criterion = "0.4"
