pub mod object_type_definitions;
pub mod auxilary_functions;
pub mod terminal_decoration;
pub mod error_types;
pub mod external_functions;
pub mod polynomials;
pub mod taylor_generation;
pub mod polynomial_operators;
pub mod taylor_optimizer;